import { Routes } from '@angular/router';

import { DashboardComponent } from '../../pages/dashboard/dashboard.component';
import { UserComponent } from '../../pages/user/user.component';
import { TableComponent } from '../../pages/table/table.component';
import { TypographyComponent } from '../../pages/typography/typography.component';
import { IconsComponent } from '../../pages/icons/icons.component';
import { MapsComponent } from '../../pages/maps/maps.component';
import { NotificationsComponent } from '../../pages/notifications/notifications.component';
import { UpgradeComponent } from '../../pages/upgrade/upgrade.component';
import { CategoryComponent } from '../../pages/category/category.component';
import { CategoriesComponent } from 'app/pages/categories/categories.component';
import { SubCategoryComponent } from 'app/pages/sub-category/sub-category.component';
import { AddMainCategoryComponent } from 'app/pages/add-main-category/add-main-category.component';
import { AddCategoriesComponent } from 'app/pages/add-categories/add-categories.component';
import { AddSubCategoryComponent } from 'app/pages/add-sub-category/add-sub-category.component';
import { ServiceProvidersComponent } from 'app/pages/service-providers/service-providers.component';
import { CustomerListComponent } from 'app/pages/customer-list/customer-list.component';
import { CustomerDetailsComponent } from 'app/pages/customer-details/customer-details.component';
import { ServiceProvidersDetailsComponent } from 'app/pages/service-providers-details/service-providers-details.component';
import { MainServicesComponent } from 'app/pages/main-services/main-services.component';
import { AppointmentsComponent } from 'app/pages/appointments/appointments.component';
import { PatientsComponent } from 'app/pages/patients/patients.component';
import { ProfileComponent } from 'app/pages/profile/profile.component';
import { PatientsRequestComponent } from 'app/pages/patients-request/patients-request.component';
import { PatientsServedComponent } from 'app/pages/patients-served/patients-served.component';
import { ServiceDetailComponent } from 'app/pages/service-detail/service-detail.component';
import { MyServicesComponent } from 'app/pages/my-services/my-services.component';
import { ConsultantsComponent } from 'app/pages/consultants/consultants.component';
import { ConsultantDetailsComponent } from 'app/pages/consultant-details/consultant-details.component';
import { MyServiceUpdateComponent } from 'app/pages/my-service-update/my-service-update.component';


export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard',      component: DashboardComponent },
    { path: 'services/:id',      component: MainServicesComponent },
    { path: 'service-detail/:id',      component: ServiceDetailComponent },
    { path: 'my-services',      component: MyServicesComponent },
    { path: 'my-service-detail/:id',      component: MyServiceUpdateComponent },
    { path: 'appointments',      component: AppointmentsComponent },
    { path: 'patients',      component: PatientsComponent },
    { path: 'patients-request',      component: PatientsRequestComponent },
    { path: 'patients-served',      component: PatientsServedComponent },
    { path: 'add-main-category',      component: AddMainCategoryComponent },
    { path: 'add-categories',      component: AddCategoriesComponent },
    { path: 'add-sub-category',      component: AddSubCategoryComponent },
    { path: 'category',      component: CategoryComponent },
    // { path: 'services',      component: CategoryComponent },
    { path: 'categories',      component: CategoriesComponent },
    { path: 'sub-category/:id',      component: SubCategoryComponent },
    { path: 'service-provider',      component: ServiceProvidersComponent },
    { path: 'service-provider-detail/:id',      component: ServiceProvidersDetailsComponent },
    { path: 'customers',      component: CustomerListComponent },
    { path: 'customer-details/:id',      component: CustomerDetailsComponent },
    { path: 'consultants',      component: ConsultantsComponent },
    { path: 'consultant-details',      component: ConsultantDetailsComponent },
    { path: 'user',           component: UserComponent },
    { path: 'table',          component: TableComponent },
    { path: 'typography',     component: TypographyComponent },
    { path: 'icons',          component: IconsComponent },
    { path: 'maps',           component: MapsComponent },
    { path: 'notifications',  component: NotificationsComponent },
    { path: 'upgrade',        component: UpgradeComponent },
    { path: 'profile',        component: ProfileComponent },
];
